[DISCORD]
prefix = ""
token = ""

[TWITCH]
prefix = ""
token = ""
channels = ["timeenjoyed"]
client_id = ""
client_secret = ""

[API]
prefix = ""
port = 2536
public_host = "http://localhost:2536/"

[DATABASE]
dsn = "postgresql://USER:PASSWORD@localhost:5432/timeenjoyed"