[DISCORD]
prefix = ""
token = ""

[TWITCH]
prefix = ""
token = ""
app_token = ""
channels = ["timeenjoyed"]
client_id = ""
client_secret = ""
eventsub_secret = ""

[API]
prefix = ""
port = 2536
public_host = "http://localhost:2536/"

[DATABASE]
dsn = "postgresql://USER:PASSWORD@localhost:5432/timeenjoyed"

[GENERAL]
stream_refs_id = 874734169622716437
announcements_id = 862800502848749609
announcements_webhook = ""
music_webhook = ""

[TIME_SUBS]
events = ["stream.online", "channel.channel_points_custom_reward_redemption.add", "channel.raid"]
twitch_id = "410885037"
online_role_id = 1167278797742157824
scopes = []

[WAVELINK]
uri = "http://localhost:2333/connect"
password = ""